---
- name: Install Apache on Agent Node
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    
    - name: Start httpd
      service:
        name: httpd
        state: starts
        enabled: yes
        
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

  